name: CI

on:
  pull_request:
    branches: [main, master, develop, development]
  push:
    branches: [feature/tests]

jobs:
  lint:
    name: Lint
    runs-on: [self-hosted, ci]
    container: node:22
    permissions:
      contents: read

    steps:
      - name: ğŸ”„ Checkout repository
        uses: actions/checkout@v4

      - name: 'âš™ï¸ Node setup'
        uses: ./.github/actions/node-setup
        with:
          node-version: '22'

      - name: âœ… Run linter
        run: npm run lint

  build:
    name: Build
    runs-on: [self-hosted, ci]
    container: node:22
    permissions:
      contents: read
    needs: [lint]

    steps:
      - name: ğŸ”„ Checkout repository
        uses: actions/checkout@v4

      - name: 'âš™ï¸ Node setup'
        uses: ./.github/actions/node-setup
        with:
          node-version: '22'

      - name: ğŸ—ï¸ Build project
        run: npm run build

  test:
    name: Test
    runs-on: [self-hosted, ci]
    container: node:22
    permissions:
      contents: read
    needs: [lint, build]

    steps:
      - name: ğŸ”„ Checkout repository
        uses: actions/checkout@v4

      - name: 'âš™ï¸ Node setup'
        uses: ./.github/actions/node-setup
        with:
          node-version: '22'

      - name: âœ… Run tests
        run: npm run test
